async function main() {
  try {
    process.exit(0);
  } catch (err) {
    console.log(err);
    process.exit(1);
  }
}

main();
